name: Populate Icons TODO

on:
  push:
    paths:
      - 'icons/src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Change to icons directory
        run: cd icons
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run populate-icons.py
        run: python populate-icons.py
      
      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add TODO.md
          git commit -m "chore: update TODO.md"
          git push